"""Added updated_at to user model

Revision ID: 25da95f73ccb
Revises: 71b2fe23da48
Create Date: 2022-08-01 20:54:11.078928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25da95f73ccb'
down_revision = '71b2fe23da48'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###
