"""create users table

Revision ID: b4b18692988d
Revises: 77ad48ffaa25
Create Date: 2022-07-06 20:11:39.919493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4b18692988d'
down_revision = '77ad48ffaa25'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('alarms', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key('alarms_user_id_fkey', 'alarms', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('alarms_user_id_fkey', 'alarms', type_='foreignkey')
    op.drop_column('alarms', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
